//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeFile.DownloadManager.UserServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServer.UserService")]
    public interface UserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/AddUser", ReplyAction="http://tempuri.org/UserService/AddUserResponse")]
        void AddUser(Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/GetAllUsers", ReplyAction="http://tempuri.org/UserService/GetAllUsersResponse")]
        Entities.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/DeleteUser", ReplyAction="http://tempuri.org/UserService/DeleteUserResponse")]
        void DeleteUser(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/GetUser", ReplyAction="http://tempuri.org/UserService/GetUserResponse")]
        Entities.User GetUser(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/EditUser", ReplyAction="http://tempuri.org/UserService/EditUserResponse")]
        void EditUser(Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/GetUsersCount", ReplyAction="http://tempuri.org/UserService/GetUsersCountResponse")]
        int GetUsersCount();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : FreeFile.DownloadManager.UserServer.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<FreeFile.DownloadManager.UserServer.UserService>, FreeFile.DownloadManager.UserServer.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(Entities.User user) {
            base.Channel.AddUser(user);
        }
        
        public Entities.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public void DeleteUser(System.Guid UserID) {
            base.Channel.DeleteUser(UserID);
        }
        
        public Entities.User GetUser(System.Guid UserID) {
            return base.Channel.GetUser(UserID);
        }
        
        public void EditUser(Entities.User user) {
            base.Channel.EditUser(user);
        }
        
        public int GetUsersCount() {
            return base.Channel.GetUsersCount();
        }
    }
}
